name: backend
on: [pull_request]
jobs:
  backend:
    defaults:
      run:
        working-directory: backend
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install packages
        run: uv sync

      - name: Run lint checks (ruff, mypy) on .py files
        run: make lint

      - name: Run tests
        run: make test
